from tkinter import *
from  PIL import Image,ImageTk

top = Tk()
top.geometry("1215x610")
top.minsize(1215,610)
top.maxsize(1215,610)
# title
top.title("super bikes")
# icon
top.iconbitmap(r"icon.ico")
# main frame
master_frame=Frame(top,background="#C1DAF4")
master_frame.pack(fill="both",expand=True)
# images
image1=Image.open("bike1.png")
image1=image1.resize((200,200), resample=Image.Resampling.LANCZOS)
image1=ImageTk.PhotoImage(image1)
image2=Image.open("bike2.png")
image2=image2.resize((200,200), resample=Image.Resampling.LANCZOS)
image2=ImageTk.PhotoImage(image2)
image3=Image.open("bike3.png")
image3=image3.resize((200,200), resample=Image.Resampling.LANCZOS)
image3=ImageTk.PhotoImage(image3)
image4=Image.open("bike6.png")
image4=image4.resize((600,600), resample=Image.Resampling.LANCZOS)
image4=ImageTk.PhotoImage(image4)
image5=Image.open("bike4.png")
image5=image5.resize((200,200), resample=Image.Resampling.LANCZOS)
image5=ImageTk.PhotoImage(image5)
image6=Image.open("bike5.png")
image6=image6.resize((200,200), resample=Image.Resampling.LANCZOS)
image6=ImageTk.PhotoImage(image6)
image7=Image.open("bike7.png")
image7=image7.resize((400,400), resample=Image.Resampling.LANCZOS)
image7=ImageTk.PhotoImage(image7)
# frames
pic_frame=Frame(master_frame)
pic_frame.grid(row=0,column=0)
pic_frame1=Frame(master_frame)
pic_frame1.grid(row=0,column=1,rowspan=2)
pic_frame2=Frame(master_frame)
pic_frame2.grid(row=0,column=2,sticky="nw")
pic_frame3=Frame(master_frame)
pic_frame3.grid(row=1,column=2,sticky="nw")
# labels
label1=Label(pic_frame,image=image1)
label1.grid(column=0,row=0)
label2=Label(pic_frame,image=image2)
label2.grid(column=0,row=1)
label3=Label(pic_frame,image=image3)
label3.grid(column=0,row=2)
label4=Label(pic_frame1,image=image4)
label4.grid(column=0,row=0,pady=5)
label5=Label(pic_frame2,image=image5)
label5.grid(column=0,row=0)
label6=Label(pic_frame2,image=image6)
label6.grid(column=1,row=0)
label7=Label(pic_frame2,image=image7)
label7.grid(column=0,row=1,columnspan=2)
top.mainloop()